@host=http://localhost:8000/api
###
# Get all professions
GET {{host}}/professions HTTP/1.1

###
# Get all sessions
GET {{host}}/sessions HTTP/1.1

###
# Get session detail
GET {{host}}/sessions/E910EC HTTP/1.1

###
# Create a session
POST {{host}}/sessions HTTP/1.1
Content-Type: application/json

###
# Delete a session
DELETE {{host}}/sessions?key=0b8c727c-17a9-47b0-8d3d-dbc22e9c511a HTTP/1.1

###
# Remove player from session
POST {{host}}/sessions/abb7be44-b7b8-42eb-9d42-8ef9c8fe402d/remove-player?player=nicha HTTP/1.1
Content-Type: application/json

###

POST {{host}}/players HTTP/1.1
Content-Type: application/json

{
    "current_sessions": "E910EC",
    "name": "wendy",
    "dreams": "Travel around the world",
    "choose_profession": "Airline Pilot"
}
